import type { Asset, Zone, Incident, Report, InspectionImage, CorrosionTrend, ZoneStats } from './types';

export const zones: Zone[] = [
  {
    id: '1',
    name: 'Zona Norte',
    city: 'Barranquilla',
    totalAssets: 45,
    critical: 4,
    moderate: 12,
    mild: 29,
    coordinates: { lat: 10.9639, lng: -74.7964 },
  },
  {
    id: '2',
    name: 'Zona Centro',
    city: 'Bogotá',
    totalAssets: 62,
    critical: 3,
    moderate: 15,
    mild: 44,
    coordinates: { lat: 4.7110, lng: -74.0721 },
  },
  {
    id: '3',
    name: 'Zona Antioquia',
    city: 'Medellín',
    totalAssets: 38,
    critical: 2,
    moderate: 8,
    mild: 28,
    coordinates: { lat: 6.2476, lng: -75.5658 },
  },
  {
    id: '4',
    name: 'Zona Pacífico',
    city: 'Cali',
    totalAssets: 41,
    critical: 3,
    moderate: 9,
    mild: 29,
    coordinates: { lat: 3.4516, lng: -76.5320 },
  },
  {
    id: '5',
    name: 'Zona Caribe',
    city: 'Cartagena',
    totalAssets: 35,
    critical: 4,
    moderate: 7,
    mild: 24,
    coordinates: { lat: 10.3910, lng: -75.4794 },
  },
  {
    id: '6',
    name: 'Zona Portuaria',
    city: 'Buenaventura',
    totalAssets: 27,
    critical: 1,
    moderate: 3,
    mild: 23,
    coordinates: { lat: 3.8801, lng: -77.0311 },
  },
];

export const assets: Asset[] = [
  {
    id: 'ACT-001',
    name: 'Estructura Principal A1',
    zone: 'Barranquilla',
    corrosionLevel: 'critico',
    lastInspection: '2025-03-28',
    trend: 'up',
    riskScore: 92,
  },
  {
    id: 'ACT-002',
    name: 'Torre de Enfriamiento B2',
    zone: 'Cartagena',
    corrosionLevel: 'critico',
    lastInspection: '2025-03-25',
    trend: 'up',
    riskScore: 88,
  },
  {
    id: 'ACT-003',
    name: 'Plataforma de Carga C3',
    zone: 'Buenaventura',
    corrosionLevel: 'moderado',
    lastInspection: '2025-03-30',
    trend: 'stable',
    riskScore: 65,
  },
  {
    id: 'ACT-004',
    name: 'Tanque de Almacenamiento D4',
    zone: 'Bogotá',
    corrosionLevel: 'critico',
    lastInspection: '2025-03-27',
    trend: 'up',
    riskScore: 85,
  },
  {
    id: 'ACT-005',
    name: 'Tubería Principal E5',
    zone: 'Medellín',
    corrosionLevel: 'moderado',
    lastInspection: '2025-03-29',
    trend: 'down',
    riskScore: 58,
  },
  {
    id: 'ACT-006',
    name: 'Estructura de Soporte F6',
    zone: 'Cali',
    corrosionLevel: 'leve',
    lastInspection: '2025-04-01',
    trend: 'stable',
    riskScore: 25,
  },
  {
    id: 'ACT-007',
    name: 'Puente Grúa G7',
    zone: 'Barranquilla',
    corrosionLevel: 'moderado',
    lastInspection: '2025-03-26',
    trend: 'up',
    riskScore: 62,
  },
  {
    id: 'ACT-008',
    name: 'Silo de Materiales H8',
    zone: 'Cartagena',
    corrosionLevel: 'critico',
    lastInspection: '2025-03-24',
    trend: 'up',
    riskScore: 90,
  },
  {
    id: 'ACT-009',
    name: 'Estructura Portuaria I9',
    zone: 'Buenaventura',
    corrosionLevel: 'leve',
    lastInspection: '2025-04-02',
    trend: 'down',
    riskScore: 18,
  },
  {
    id: 'ACT-010',
    name: 'Columna Industrial J10',
    zone: 'Bogotá',
    corrosionLevel: 'moderado',
    lastInspection: '2025-03-31',
    trend: 'stable',
    riskScore: 55,
  },
];

export const incidents: Incident[] = [
  {
    id: 'INC-001',
    assetId: 'ACT-001',
    assetName: 'Estructura Principal A1',
    zone: 'Barranquilla',
    severity: 'critico',
    description: 'Corrosión severa detectada en juntas de soldadura. Requiere intervención inmediata.',
    detectedAt: '2025-04-08',
    assignedTo: 'Carlos Mendoza',
    status: 'abierto',
  },
  {
    id: 'INC-002',
    assetId: 'ACT-002',
    assetName: 'Torre de Enfriamiento B2',
    zone: 'Cartagena',
    severity: 'critico',
    description: 'Degradación acelerada en base de torre. Riesgo estructural identificado.',
    detectedAt: '2025-04-07',
    assignedTo: 'Ana María López',
    status: 'en-progreso',
  },
  {
    id: 'INC-003',
    assetId: 'ACT-008',
    assetName: 'Silo de Materiales H8',
    zone: 'Cartagena',
    severity: 'critico',
    description: 'Oxidación avanzada en paneles laterales. Evaluación estructural requerida.',
    detectedAt: '2025-04-06',
    assignedTo: 'Jorge Ramírez',
    status: 'abierto',
  },
  {
    id: 'INC-004',
    assetId: 'ACT-004',
    assetName: 'Tanque de Almacenamiento D4',
    zone: 'Bogotá',
    severity: 'moderado',
    description: 'Corrosión en válvulas de acceso. Requiere reemplazo programado.',
    detectedAt: '2025-04-05',
    assignedTo: 'María Fernanda Díaz',
    status: 'en-progreso',
  },
  {
    id: 'INC-005',
    assetId: 'ACT-007',
    assetName: 'Puente Grúa G7',
    zone: 'Barranquilla',
    severity: 'moderado',
    description: 'Deterioro en rieles de desplazamiento. Mantenimiento preventivo necesario.',
    detectedAt: '2025-04-03',
    assignedTo: 'Pedro Sánchez',
    status: 'resuelto',
  },
];

export const reports: Report[] = [
  {
    id: 'RPT-001',
    title: 'Reporte Mensual - Marzo 2025',
    type: 'mensual',
    date: '2025-04-01',
    fileSize: '2.4 MB',
  },
  {
    id: 'RPT-002',
    title: 'Reporte Mensual - Febrero 2025',
    type: 'mensual',
    date: '2025-03-01',
    fileSize: '2.1 MB',
  },
  {
    id: 'RPT-003',
    title: 'Reporte Trimestral Q1 2025',
    type: 'trimestral',
    date: '2025-04-05',
    fileSize: '5.8 MB',
  },
  {
    id: 'RPT-004',
    title: 'Reporte Anual 2024',
    type: 'anual',
    date: '2025-01-15',
    fileSize: '12.3 MB',
  },
  {
    id: 'RPT-005',
    title: 'Reporte Trimestral Q4 2024',
    type: 'trimestral',
    date: '2025-01-10',
    fileSize: '5.2 MB',
  },
  {
    id: 'RPT-006',
    title: 'Reporte Mensual - Enero 2025',
    type: 'mensual',
    date: '2025-02-01',
    fileSize: '1.9 MB',
  },
];

export const inspectionImages: InspectionImage[] = [
  {
    id: 'IMG-001',
    assetId: 'ACT-001',
    assetName: 'Estructura Principal A1',
    zone: 'Barranquilla',
    severity: 'critico',
    date: '2025-03-28',
    imageUrl: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400&h=300&fit=crop',
    notes: 'Corrosión severa visible en juntas',
  },
  {
    id: 'IMG-002',
    assetId: 'ACT-002',
    assetName: 'Torre de Enfriamiento B2',
    zone: 'Cartagena',
    severity: 'critico',
    date: '2025-03-25',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop',
    notes: 'Degradación en base estructural',
  },
  {
    id: 'IMG-003',
    assetId: 'ACT-003',
    assetName: 'Plataforma de Carga C3',
    zone: 'Buenaventura',
    severity: 'moderado',
    date: '2025-03-30',
    imageUrl: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=400&h=300&fit=crop',
    notes: 'Oxidación moderada en superficie',
  },
  {
    id: 'IMG-004',
    assetId: 'ACT-005',
    assetName: 'Tubería Principal E5',
    zone: 'Medellín',
    severity: 'moderado',
    date: '2025-03-29',
    imageUrl: 'https://images.unsplash.com/photo-1518640467707-6811f4a6ab73?w=400&h=300&fit=crop',
    notes: 'Corrosión en uniones de tubería',
  },
  {
    id: 'IMG-005',
    assetId: 'ACT-006',
    assetName: 'Estructura de Soporte F6',
    zone: 'Cali',
    severity: 'leve',
    date: '2025-04-01',
    imageUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400&h=300&fit=crop',
    notes: 'Estado general bueno',
  },
  {
    id: 'IMG-006',
    assetId: 'ACT-008',
    assetName: 'Silo de Materiales H8',
    zone: 'Cartagena',
    severity: 'critico',
    date: '2025-03-24',
    imageUrl: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=400&h=300&fit=crop',
    notes: 'Oxidación avanzada en paneles',
  },
  {
    id: 'IMG-007',
    assetId: 'ACT-009',
    assetName: 'Estructura Portuaria I9',
    zone: 'Buenaventura',
    severity: 'leve',
    date: '2025-04-02',
    imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=400&h=300&fit=crop',
    notes: 'Sin hallazgos significativos',
  },
  {
    id: 'IMG-008',
    assetId: 'ACT-010',
    assetName: 'Columna Industrial J10',
    zone: 'Bogotá',
    severity: 'moderado',
    date: '2025-03-31',
    imageUrl: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=400&h=300&fit=crop',
    notes: 'Requiere monitoreo continuo',
  },
];

export const corrosionTrends: CorrosionTrend[] = [
  { month: 'Oct', critical: 12, moderate: 45, mild: 165 },
  { month: 'Nov', critical: 14, moderate: 48, mild: 168 },
  { month: 'Dic', critical: 13, moderate: 50, mild: 170 },
  { month: 'Ene', critical: 15, moderate: 52, mild: 172 },
  { month: 'Feb', critical: 16, moderate: 51, mild: 175 },
  { month: 'Mar', critical: 17, moderate: 54, mild: 177 },
];

export const zoneStats: ZoneStats[] = [
  { zone: 'Barranquilla', critical: 4, moderate: 12, mild: 29 },
  { zone: 'Bogotá', critical: 3, moderate: 15, mild: 44 },
  { zone: 'Medellín', critical: 2, moderate: 8, mild: 28 },
  { zone: 'Cali', critical: 3, moderate: 9, mild: 29 },
  { zone: 'Cartagena', critical: 4, moderate: 7, mild: 24 },
  { zone: 'Buenaventura', critical: 1, moderate: 3, mild: 23 },
];

export const dashboardMetrics = {
  totalAssets: 248,
  criticalAssets: 17,
  moderateAssets: 54,
  mildAssets: 177,
  activeIncidents: 3,
  resolvedThisMonth: 8,
  avgResponseTime: '2.4 horas',
  systemUptime: 99.8,
};
